[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lottery = "B1xS2zq7MFpNuQvzm7VYjr54JUuaMrxCoVjRtw2oJvMr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/typhon/solwallettest.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
