[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
lottery = "E5Tmweyj2XLDn1L746PPdt7dAbG397qvTj8wYBqEaBSX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#cluster = "devnet"
wallet = "/Users/typhon/solwallettest.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
